'use client';
import type { PricingLine } from '@/types/pricing-options.type';
export const formatPrice = (amount: number) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 2 }).format(amount);
// Para los importes grandes del cobro: «$ 38.000» se lee de un vistazo; los centavos solo aparecen si los hay.
export const formatImporte = (amount: number) => Number.isInteger(amount) ? new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(amount) : formatPrice(amount);
const time = (value: string) => new Date(value).toLocaleString('es-AR', { timeZone: 'America/Argentina/Buenos_Aires', hour: '2-digit', minute: '2-digit', day: '2-digit', month: '2-digit' });
export function PricingBreakdown({ lines, total }: { lines: PricingLine[]; total: number }) {
  return <div className="space-y-2"><ol className="divide-y rounded-xl border px-3">{lines.map((line, index) => <li key={index} className="py-3 text-sm flex items-start justify-between gap-3"><div><p>{line.label}</p>{line.dayType && <p className="text-xs text-muted-foreground">{line.dayType === 'DAY' ? 'Precio de día' : 'Precio de noche'}{line.startAt && line.endAt ? ` · ${time(line.startAt)} a ${time(line.endAt)}` : ''}</p>}{line.unitPrice !== undefined && <p className="text-xs text-muted-foreground">{Number((line.minutes ?? 0).toFixed(2))} minutos · precio por unidad: {formatPrice(line.unitPrice)}{Number.isInteger(line.units) ? ` · ${line.units} ${line.units === 1 ? 'unidad cobrada' : 'unidades cobradas'}` : ''}</p>}{line.minutes !== undefined && !line.dayType && <p className="text-xs text-muted-foreground">{line.minutes} minutos</p>}</div><span className="whitespace-nowrap font-medium">{line.amount === 0 ? '—' : formatPrice(line.amount)}</span></li>)}</ol><div className="flex justify-between text-base font-semibold px-3"><span>Total de la estadía</span><span>{formatPrice(total)}</span></div></div>;
}
